services:
  free-games-claimer:
    image: free-games-claimer
    container_name: fgc
    build: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "6080:6080"
    volumes:
      - fgc_data:/fgc/data
    command: bash -c "node steam-games; node epic-games; node prime-gaming; node gog; echo sleeping; sleep 1d"

    healthcheck: # see Dockerfile, check that node is running and noVNC is reachable
      test: pgrep node && curl --fail http://localhost:6080 || exit 1
      interval: 5s
      timeout: 5s

    # --- CONFIGURATION (According to image 1) ---
    # Uncomment the variables you want to set.
    environment:
      # Display Options / VNC
      - SHOW=1                  # 1 = Show browser (required for VNC)
      - WIDTH=1920              # VNC screen width
      - HEIGHT=1080             # VNC screen height
      # - VNC_PASSWORD=         # Password for VNC connection (default empty)

      # Notifications (Apprise)
      # - NOTIFY=               # Notification service URL (e.g., tgram://...)
      # - NOTIFY_TITLE=         # Notification title

      # Default login data (used if specific store data is not provided)
      # - EMAIL=                # Your email
      # - PASSWORD=             # Your password

      # Steam (Overrides default)
      # - STEAM_USERNAME=       # Optional: Your login (not email), if you want automatic login
      # - STEAM_PASSWORD=       # Optional: Your password

      # Epic Games (Overrides default)
      # - EG_EMAIL=
      # - EG_PASSWORD=
      # - EG_OTPKEY=            # MFA/2FA Key (if you use it)
      # - EG_PARENTALPIN=       # Parental control PIN
      
      # Prime Gaming (Overrides default)
      # - PG_EMAIL=
      # - PG_PASSWORD=
      # - PG_OTPKEY=            # MFA/2FA Key
      # - PG_REDEEM=0           # 1 = Try to redeem keys in external stores (experimental)
      # - PG_REDEEM_JSON=1   # 1 = Retroactively redeem unclaimed GOG codes
      # - PG_CLAIMDLC=0         # 1 = Also claim DLCs (experimental)
      
      # GOG (Overrides default)
      # - GOG_EMAIL=
      # - GOG_PASSWORD=
      # - GOG_NEWSLETTER=0      # 1 = Do not unsubscribe from newsletter after claiming a game
      
      # Other settings
      # - TIMEOUT=60            # Action timeout on page
      # - LOGIN_TIMEOUT=100     # Time to login (auto + manual)
      # - BROWSER_DIR=data/browser # Browser profile path

volumes:
  fgc_data:

