name: Lint Code Base
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: super-linter/super-linter/slim@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_MARKDOWN: true
          VALIDATE_TYPESCRIPT: false  # Falls kein TS
