name: Sonar

on:
  # Trigger analysis when pushing in main or pull requests, and when creating a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting. Otherwise sonarcloud will show a warning.
        fetch-depth: 0
    -
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
    -
      name: Install dev dependencies which includde ESLint + plugins
      run: npm install --only=dev
    -
      name: Run ESLint
      continue-on-error: true
      run: npx eslint . -f json -o eslint_report.json
    -
      name: Fix ESLint paths
      run: sed -i 's+/home/runner/work/free-games-claimer/free-games-claimer+/github/workspace+g' eslint_report.json
    -
      name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
